language: node_js
node_js:
    - "stable"
sudo: false
install:
    - npm install -g tslint tsd typescript
    - npm install
    - tsd install
    - tslint --version
    - ./node_modules/.bin/tsc --version
script:
    - tslint src/main.tsx
    - ./node_modules/.bin/tsc -p src/
